spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}        
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                id:
                    new_generator_mappings: false
                format_sql: true
                hbm2ddl:
                    auto: update
    mvc:
        view:
            prefix: /WEB-INFO/views/
            suffix : .jsp
        static-path-pattern: /resources/*
