image: maven:3.6.1
pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - cd project_code/
          - mvn clean install
        artifacts:
           - target/debitcardcustomer-0.0.1-SNAPSHOT.war
             
    - step:
         name: deployment
         deployment: production
         caches:
           - maven
         script:
                  - ./deploy-my-app.sh