version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - sudo apt-get install -y maven

  pre_build:
    commands:
      - cd project_code
      - mvn clean

  build:
    commands:
      - cd project_code
      - mvn install

artifacts:
  files: project_code/target/*.war
