name: ci/cd pipeline for debitcard app
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: provide the env details 
    # secrets:
    #   db_host:
    #     required: true
    #   db_name:
    #     required: true
    #   db_user:
    #     required: true
    #   db_pass:
    #     required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
 
    - name: generate version
      run: |
        commitid=$(git rev-parse --short HEAD)
        semanticVersion="1.0.0"
        #export Ver=$semanticVersion-$commitid
        echo "VERSION=$semanticVersion-$commitid" >> $GITHUB_ENV
        #echo "$Ver"
    - name: print env
      run: echo "$VERSION"
    - name: Build with Maven
      env:
        # DB_HOST: ${{ secrets.db_host }}
        # DB_NAME: ${{ secrets.db_name }}
        # DB_USER: ${{ secrets.db_user }}
        # DB_PASS: ${{ secrets.db_pass }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: |
        cd project_code
        mvn compile

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar.java.binaries: ${{ GITHUB.WORKSPACE }}/project_code/target/classes
        args: >
          -Dsonar.projectKey=shyam
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        

    - name: upload artifact 
      uses: actions/upload-artifact@v3
      with:
        name: warfile-${{ env.VERSION }}
        path: |
          ${{ GITHUB.WORKSPACE }}/project_code/target/**.war
    

    - name: Upload Build Artifact to Jfrog 
      run: |
        curl -u ${{ secrets.JFROG_USER }}:${{ secrets.JFROG_PASS }} -X PUT "http://18.116.72.114:8081/artifactory/generic-local/shyam/debitcard/debitcardapp.${{ env.VERSION }}.war" -T ${{ github.workspace }}/project_code/target/*.war




