on:
  push:
    branches: workflow
  pull_request:
    type: [opened]
    branches:
      - master
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd project_code
        mvn -B package --file pom.xml
