name: ci/cd pipeline for debitcard app
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: provide the env details 
    # secrets:
    #   db_host:
    #     required: true
    #   db_name:
    #     required: true
    #   db_user:
    #     required: true
    #   db_pass:
    #     required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        VERSION: 1.0.0
        # DB_HOST: ${{ secrets.db_host }}
        # DB_NAME: ${{ secrets.db_name }}
        # DB_USER: ${{ secrets.db_user }}
        # DB_PASS: ${{ secrets.db_pass }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
      run: |
        cd project_code
        mvn clean install 
    - name: Print DB Host
      run: |
        echo "DB_HOST: ${{ secrets.DB_HOST }}" > secrets.txt
        cat secrets.txt

    - name: Debug Secrets
      run: |
        echo "DB_HOST: ${{ secrets.DB_HOST  }}" >> debug_secrets.log
        echo "DB_NAME: ${{ secrets.DB_NAME }}" >> debug_secrets.log
        echo "DB_USER: ${{ secrets.DB_USER }}" >> debug_secrets.log
        echo "DB_PASS: ${{ secrets.DB_PASS }}" >> debug_secrets.log
    - name: Upload Secrets Log
      uses: actions/upload-artifact@v3
      with:
        name: debug-secrets-log
        path: debug_secrets.log

    


