name: build app
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "env details"
        type: string

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      db_host: ${{ secrets.DB_HOST }}
      db_name: ${{ secrets.DB_NAME }}
      db_user: ${{ secrets.DB_USER }}
      db_pass: ${{ secrets.DB_PASS }}
  # creds:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Debug Secrets
  #     run: |
  #       echo "DB_HOST: ${{ secrets.DB_HOST }}" >> debug_secrets.log
  #       echo "DB_NAME: ${{ secrets.DB_NAME }}" >> debug_secrets.log
  #       echo "DB_USER: ${{ secrets.DB_USER }}" >> debug_secrets.log
  #       echo "DB_PASS: ${{ secrets.DB_PASS }}" >> debug_secrets.log
  #   - name: Upload Secrets Log
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: debug-secrets-log
  #       path: debug_secrets.log