name: build app
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "env details"
        type: string
jobs:
  build:
    uses: ./.github/workflows/main.yaml
    with:
      environment: ${{ github.event.inputs.environment }}