name: build app
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "env details"
        type: string

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit
    # secrets:
    #   db_host: ${{ secrets.DB_HOST }}
    #   db_name: ${{ secrets.DB_NAME }}
    #   db_user: ${{ secrets.DB_USER }}
    #   db_pass: ${{ secrets.DB_PASS }}
